#!/bin/sh
export GEM_HOME={{pkg.path}}/lib/ruby/2.5.0
export GEM_PATH={{pkgPathFor ruby}}/lib/ruby/2.5.0

runlist=""
{{#each cfg.runlist}}
runlist="$runlist,{{this}}"
{{/each}}

{{#if cfg.splay ~}}
  splay={{cfg.splay}}
{{else ~}}
  splay=1
{{/if ~}}
{{#if cfg.interval ~}}
  interval={{cfg.interval}}
  sleep $((RANDOM % splay))
  while true; do
  APPBUNDLER_ALLOW_RVM="true" chef-client \
    --runlist "${runlist#,}" \
    --config "{{pkg.svc_config_path}}/client.rb"
  sleep $interval
  done
{{else ~}}
  APPBUNDLER_ALLOW_RVM="true" chef-client \
    --runlist "${runlist#,}" \
    --config "{{pkg.svc_config_path}}/client.rb"
{{/if ~}}
