#!/bin/bash

exec 2>&1

cd "{{pkg.svc_path}}"

if [[ -n "{{cfg.advertise-address}}" ]]; then
  advertise_address="{{cfg.advertise-address}}"
fi

etcd_servers="{{#each bind.kvstore.members as |member| ~}}https://{{member.sys.ip}}:{{member.cfg.client-port}},{{/each ~}}"
members=({{#each svc.members as |member| ~}}{{member.sys.hostname ~}} {{/each ~}})

exec {{pkgPathFor "ncerny/kubernetes"}}/bin/kube-apiserver \
  --admission-control=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,AlwaysPullImages \
  --advertise-address="{{sys.ip}}" \
  --allow-privileged=true \
  --apiserver-count="${#members[*]}" \
  --enable-swagger-ui=true \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/audit.log \
  --authorization-mode=Node,RBAC \
  --bind-address="0.0.0.0" \
  --secure-port={{cfg.secure-port}} \
  --client-ca-file="{{pkg.svc_static_path}}/ca.pem" \
  --enable-swagger-ui=true \
  --etcd-cafile="{{pkg.svc_static_path}}/ca.pem" \
  --etcd-certfile="{{pkg.svc_static_path}}/{{sys.hostname}}.pem" \
  --etcd-keyfile="{{pkg.svc_static_path}}/{{sys.hostname}}-key.pem" \
  --etcd-servers="${etcd_servers%?}" \
  --event-ttl=1h \
  --experimental-encryption-provider-config="{{pkg.svc_files_path}}/encryption-config.yaml" \
  --insecure-bind-address="127.0.0.1" \
  --kubelet-certificate-authority="{{pkg.svc_static_path}}/ca.pem" \
  --kubelet-client-certificate="{{pkg.svc_static_path}}/{{sys.hostname}}.pem" \
  --kubelet-client-key="{{pkg.svc_static_path}}/{{sys.hostname}}-key.pem" \
  --kubelet-https=true \
  --runtime-config="api/all,admissionregistration.k8s.io/v1alpha1" \
  --service-cluster-ip-range="{{cfg.service-cluster-ip-range}}" \
  --service-node-port-range="{{cfg.service-node-port-range}}" \
  --cert-dir="{{pkg.svc_static_path}}" \
  --tls-ca-file="{{pkg.svc_static_path}}/ca.pem" \
  --tls-cert-file="{{pkg.svc_files_path}}/kubernetes.pem" \
  --tls-private-key-file="{{pkg.svc_files_path}}/kubernetes-key.pem" \
  --v=2
