# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.

controller = "controller.example.com"

[kubelet]
allow-privileged = true
anonymous-auth = false
authorization-mode = "Webhook"
cluster-dns = "10.32.0.10"
cluster-domain = "kubernetes.local"
image-pull-progress-deadline = "2m"
runtime-request-timeout = "15m"
v = 2

[apiserver]
service-cluster-ip-range = "10.32.0.0/24"
service-node-port-range = "30000-32767"
secure-port = "443"
address = "127.0.0.1"
bind-address = "127.0.0.1"
apiserver-count = 3
enable-admission-plugins = "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
allow-privileged = true
authorization-mode = "Node,RBAC"
etcd-servers = "http://127.0.0.1:2379"
enable-swagger-ui = true
audit-log-maxage = 30
audit-log-maxbackup = 3
audit-log-maxsize = 100
audit-log-path = "/var/log/audit.log"
event-ttl = "1h"
runtime-config = "api/all,admissionregistration.k8s.io/v1alpha1"
v = 2
