#!/bin/bash

ca_update '{{pkg.svc_static_path}}/ca'
if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-server.pem {{sys.hostname}} {{sys.ip}}) ]]; then
	cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-server.pem server {{pkg.svc_config_path}}/csr.json
fi
if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-client.pem {{sys.hostname}} {{sys.ip}}) ]]; then
	cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-client.pem client {{pkg.svc_config_path}}/csr.json
fi
if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-peer.pem {{sys.hostname}} {{sys.ip}}) ]]; then
	cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-peer.pem peer {{pkg.svc_config_path}}/csr.json
fi
