#!/bin/bash

exec 2>&1

proto="{{cfg.etcd-http-proto}}"

cd {{pkg.svc_path}}

if [[ "{{cfg.etcd-auto-tls}}" == "true" ]]; then
	export ETCD_AUTO_TLS="true"
	export ETCD_PEER_AUTO_TLS="true"
else
  if [[ "{{cfg.etcd-client-cert-auth}}" == "true" ]]; then
    export ETCD_CLIENT_CERT_AUTH="true"
		if [[ -n "{{cfg.etcd-client-cert-path}}" ]]; then
    	export ETCD_CERT_FILE="{{cfg.etcd-client-cert-path}}/{{sys.hostname}}.pem"
    	export ETCD_KEY_FILE="{{cfg.etcd-client-cert-path}}/{{sys.hostname}}-key.pem"
    	export ETCD_TRUSTED_CA_FILE="{{cfg.etcd-client-cert-path}}/ca.pem"
		else
			ca_update '{{pkg.svc_static_path}}/ca'
			if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-server.pem {{sys.hostname}} {{sys.ip}}) ]]; then
				cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-server.pem server {{pkg.svc_config_path}}/csr.json
			fi
			if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-client.pem {{sys.hostname}} {{sys.ip}}) ]]; then
				cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-client.pem client {{pkg.svc_config_path}}/csr.json
			fi
			export ETCD_CERT_FILE="{{pkg.svc_static_path}}/{{sys.hostname}}-server.pem"
    	export ETCD_KEY_FILE="{{pkg.svc_static_path}}/{{sys.hostname}}-server-key.pem"
    	export ETCD_TRUSTED_CA_FILE="{{pkg.svc_static_path}}/ca.pem"
		fi
  fi
  if [[ "{{cfg.etcd-peer-client-cert-auth}}" == "true" ]]; then
		export ETCD_PEER_CLIENT_CERT_AUTH="true"
		if [[ -n "{{cfg.etcd-client-cert-path}}" ]]; then
	    export ETCD_PEER_CERT_FILE="{{cfg.etcd-peer-client-cert-path}}/{{sys.hostname}}.pem"
	    export ETCD_PEER_KEY_FILE="{{cfg.etcd-peer-client-cert-path}}/{{sys.hostname}}-key.pem"
	    export ETCD_PEER_TRUSTED_CA_FILE="{{cfg.etcd-peer-client-cert-path}}/ca.pem"
		else
			ca_update '{{pkg.svc_static_path}}/ca'
			if [[ ! $(cert_verify {{pkg.svc_static_path}}/{{sys.hostname}}-peer.pem {{sys.hostname}} {{sys.ip}}) ]]; then
				cert_gen {{pkg.svc_static_path}}/{{sys.hostname}}-peer.pem peer {{pkg.svc_config_path}}/csr.json
			fi
			export ETCD_PEER_CERT_FILE="{{pkg.svc_static_path}}/{{sys.hostname}}-peer.pem"
			export ETCD_PEER_KEY_FILE="{{pkg.svc_static_path}}/{{sys.hostname}}-peer-key.pem"
			export ETCD_PEER_TRUSTED_CA_FILE="{{pkg.svc_static_path}}/ca.pem"
		fi
  fi
fi

listen_ip="{{sys.ip}}"
if [[ -n "{{cfg.etcd-listen-host-ip}}" ]]; then
  listen_ip="{{cfg.etcd-listen-host-ip}}"
fi

nodes="{{#each svc.members as |member| ~}}{{member.sys.hostname}}=${proto}://{{member.sys.ip}}:{{../cfg.etcd-server-end}},{{/each ~}}"
if [[ -n "{{cfg.etcd-initial-cluster}}" ]]; then
  nodes="{{cfg.etcd-initial-cluster}}"
fi

export ETCD_NAME="{{sys.hostname}}"
export ETCD_DATA_DIR="{{pkg.svc_data_path}}"
export ETCD_LISTEN_CLIENT_URLS="${proto}://${listen_ip}:{{cfg.etcd-client-end}}"
export ETCD_LISTEN_PEER_URLS="${proto}://${listen_ip}:{{cfg.etcd-server-end}}"
export ETCD_ADVERTISE_CLIENT_URLS="${proto}://${listen_ip}:{{cfg.etcd-client-end}}"
export ETCD_INITIAL_ADVERTISE_PEER_URLS="${proto}://${listen_ip}:{{cfg.etcd-server-end}}"
export ETCD_INITIAL_CLUSTER_TOKEN="{{cfg.etcd-initial-cluster-token}}"
export ETCD_INITIAL_CLUSTER_STATE="{{cfg.etcd-initial-cluster-state}}"
export ETCD_INITIAL_CLUSTER="$nodes"

if [[ -n "{{cfg.etcd-env-vars-file}}" ]]; then
  source "{{cfg.etcd-env-vars-file}}"
fi

exec etcd
