#!/bin/sh

cat > {{pkg.svc_config_path}}/client.rb << EOF
# Set by Build Configuration
node_name "{{sys.hostname}}-{{sys.member_id}}-{{pkg.name}}"
chef_repo_path "{{pkg.svc_data_path}}"
cookbook_path ["{{pkg.path}}/cookbooks", "{{pkgPathFor "ncerny/chef"}}/lib/cookbooks"]
data_bag_path "{{pkg.path}}/data_bags"
node_path "{{pkg.svc_data_path}}/nodes"
role_path "{{pkg.path}}/roles"
environment_path "{{pkg.path}}/environments"
cache_path "{{pkg.svc_data_path}}/cache"
file_cache_path "{{pkg.svc_data_path}}/cache/files"
file_backup_path "{{pkg.svc_data_path}}/cache/backup"
log_location "{{pkg.svc_path}}/logs/client.log"

# Set by User Configuration
{{#each cfg.configuration ~}}
{{#if this ~}}
{{@key}} {{this}}
{{else ~}}
{{@key}}
{{/if ~}}
{{/each ~}}
EOF

mkdir -p {{pkg.svc_data_path}}/nodes

export GEM_HOME={{pkgPathFor "ncerny/chef"}}/lib/ruby/2.4.0
export GEM_PATH={{pkgPathFor "core/ruby24"}}/lib/ruby/2.4.0:$GEM_HOME

APPBUNDLER_ALLOW_RVM="true" exec chef-client \
  --local-mode --once \
  --override-runlist 'recipe[smoke_test]' \
  --config {{pkg.svc_config_path}}/client.rb
