#!/bin/bash
if [[ -z "$VERBOSITY" ]]; then VERBOSITY=3; fi
if [[ -z "$FMT" ]]; then FMT="%Y/%m/%d %H:%M:%S"; fi

alias jq={{pkgPathFor "core/jq-static"}}/bin/jq

# Certificate State Constants
CERT_VALID=0
CERT_NOEXIST=1
CERT_INVALID=2
CERT_EXPIRED=3

{{#with svc.leader as |leader|}}
	export ca_url='http://{{leader.sys.ip}}:{{leader.cfg.api}}/api/v1/cfssl'
{{/with ~}}

join_by() { local IFS="$1"; shift; echo "$*"; }
log_error() { if [ "$VERBOSITY" -ge 0 ]; then echo "$(date +"$FMT") [ERROR] $*"; fi }
log_warn()  { if [ "$VERBOSITY" -ge 2 ]; then echo "$(date +"$FMT") [WARN ] $*"; fi }
log_info()  { if [ "$VERBOSITY" -ge 3 ]; then echo "$(date +"$FMT") [INFO ] $*"; fi }
log_debug() { if [ "$VERBOSITY" -ge 9 ]; then echo "$(date +"$FMT") [DEBUG] $*"; fi }
log() {
	case "${1^^}" in
	  "ERROR")
	    shift
	    log_error $*
	    ;;
	  "WARN")
	    shift
	    log_warn $*
	    ;;
	  "INFO")
	    shift
	    log_info $*
	    ;;
	  "DEBUG")
	    shift
	    log_debug $*
	    ;;
	  *)
			if [ "$VERBOSITY" -ge 1 ]; then
	    	echo "$(date +"$FMT") [LOG  ] $*"
			fi
	    ;;
	esac
}
