#!/bin/bash

exec 2>&1

{{pkgPathFor "core/kmod"}}/bin/modprobe overlay
if [ "$?" -ne 0 ]; then
  echo "overlay module not loaded!"
fi

exec containerd \
  --config {{pkg.svc_config_path}}/config.toml \
  --root {{pkg.svc_data_path}} \
  --address {{pkg.svc_var_path}}/containerd.sock
  
