#!/bin/bash

dir="{{pkg.svc_files_path}}"
ca="${dir}/ca.pem"
key="${dir}/ca-key.pem"

cd {{pkg.svc_data_path}}

{{~#if svc.me.follower}}
  if [ ! -f "$ca" ]; then
    sleep 1
    exit 1
  fi
{{~else}}
  source /hab/svc/cfssl/config/cfssl_common
  group="{{pkg.name}}.$(awk '/group/ { print $3 }' /hab/sup/default/specs/{{pkg.name}}.spec)"
  group=${group//\"/}
  log info "Checking Certificate Authority validity."
  case $(cert_verify_local ${ca}) in
    "CERT_VALID")
      log info "Certificate Authority is valid."
      ;;
    "CERT_EXPIRED")
      log info "Renewing current certificate authority."
      cfssl gencert -renewca -ca "${ca}" -ca-key "${key}" -config "{{pkg.svc_config_path}}/config.json" | cfssljson -bare ca
      cert_upload ${group} ca.pem ca-key.pem
      rm ca.pem ca-key.pem
      ;;
    *)
      log info "Generating new certificate authority."
      cfssl gencert -initca "{{pkg.svc_config_path}}/ca-csr.json" -config "{{pkg.svc_config_path}}/config.json" | cfssljson -bare ca
      cert_upload ${group} ca.pem ca-key.pem
      rm ca.pem ca-key.pem ca.csr
	    ;;
  esac
{{/if ~}}
