#!/bin/bash
exec 2>&1

cd {{pkg.svc_data_path}}

exec cfssl serve \
  -address {{sys.ip}} \
  -port {{cfg.api.port}} \
  -ca {{pkg.svc_files_path}}/ca.pem \
  -ca-key {{pkg.svc_files_path}}/ca-key.pem \
  -int-dir {{pkg.svc_files_path}} \
  -config {{pkg.svc_config_path}}/config.json
