#!/bin/sh
export GEM_HOME={{pkgPathFor "ncerny/chef"}}/lib/ruby/2.4.0
export GEM_PATH={{pkgPathFor "core/ruby24"}}/lib/ruby/2.4.0:$GEM_HOME

APPBUNDLER_ALLOW_RVM="true" exec chef-client \
  --runlist "recipe[{{pkg.name}}::default]" \
  --config "{{pkg.svc_config_path}}/client.rb"
