#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

cd {{pkg.svc_path}}

exec kubelet \
  {{#each cfg.kublet ~}}
    --{{@key}}="{{this}}" \
  {{/each ~}}
  --client-ca-file={{pkg.svc_static_path}}/ca.pem \
  --kubeconfig={{pkg.svc_config_path}}/kubeconfig \
  --config={{pkg.svc_config_path}}/manifests \
  --network-plugin=cni \
  --register-node=true \
  --tls-cert-file={{pkg.svc_static_path}}/{{sys.hostname}}.pem \
  --tls-private-key-file={{pkg.svc_static_path}}/{{sys.hostname}}-key.pem
