#!/bin/bash

exec 2>&1

cd {{pkg.svc_path}}

exec kubelet \
  --allow-privileged=true \
  --anonymous-auth=false \
  --authorization-mode=Webhook \
  --client-ca-file="{{pkg.svc_static_path}}/ca.pem" \
  --cloud-provider= \
  --cluster-dns=10.32.0.10 \
  --cluster-domain=cluster.local \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/cri-containerd.sock \
  --image-pull-progress-deadline=2m \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --pod-cidr=${POD_CIDR} \
  --register-node=true \
  --runtime-request-timeout=15m \
  --tls-cert-file=/var/lib/kubelet/${HOSTNAME}.pem \
  --tls-private-key-file=/var/lib/kubelet/${HOSTNAME}-key.pem \
  --v=2
