#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

cd {{pkg.svc_path}}

exec kubelet \
  --allow-privileged=true \
  --anonymous-auth=false \
  --authorization-mode=Webhook \
  --client-ca-file="{{pkg.svc_static_path}}/ca.pem" \
  --cloud-provider= \
  --cluster-dns=10.32.0.10 \
  --cluster-domain=kubernetes.local \
  --container-runtime=remote \
  --container-runtime-endpoint=unix://{{pkg.svc_path}}/../containerd/var/containerd.sock \
  --image-pull-progress-deadline=2m \
  --kubeconfig={{pkg.svc_config_path}}/kubeconfig \
  --network-plugin=cni \
  --register-node=true \
  --runtime-request-timeout=15m \
  --tls-cert-file={{pkg.svc_static_path}}/{{sys.hostname}}.pem \
  --tls-private-key-file={{pkg.svc_static_path}}/{{sys.hostname}}-key.pem \
  --v=2
